import { Product } from "@/types/product";
import { v4 as uuidv4 } from 'uuid';

/**
 * Generates additional headset products for the expanded catalog
 * @returns Array of headset products
 */
export function generateAdditionalHeadsets(): Product[] {
  return [
    {
      id: "audeze-maxwell",
      name: "Audeze Maxwell Wireless",
      description: "Premium wireless gaming headset with planar magnetic drivers",
      category: "headsets",
      price: 299.99,
      url_slug: "audeze-maxwell",
      image_url: "/images/products/audeze-maxwell.jpg",
      imageUrl: "/images/products/audeze-maxwell.jpg",
      specifications: {
        "Drivers": "90mm Planar Magnetic",
        "Frequency Response": "10Hz-50kHz",
        "Battery Life": "Up to 80 hours",
        "Connectivity": "2.4GHz Wireless, Bluetooth 5.3, USB-C, 3.5mm",
        "Microphone": "Detachable boom mic with AI noise filtering",
        "Features": "Dolby Atmos, Hi-Res Audio certified"
      },
      created_at: "2023-05-20T00:00:00Z",
      updated_at: "2023-10-25T00:00:00Z",
      rating: 4.8,
      review_count: 140,
      reviews: [],
      threads: [],
      upvotes: 390,
      downvotes: 15,
      score: 375,
      rank: 1
    },
    {
      id: "steelseries-arctis-nova-pro",
      name: "SteelSeries Arctis Nova Pro Wireless",
      description: "Premium wireless gaming headset with hot-swappable batteries and active noise cancellation",
      category: "headsets",
      price: 349.99,
      url_slug: "steelseries-arctis-nova-pro",
      image_url: "/images/products/arctis-nova-pro.jpg",
      imageUrl: "/images/products/arctis-nova-pro.jpg",
      specifications: {
        "Drivers": "40mm High Fidelity",
        "Frequency Response": "10Hz-40kHz",
        "Battery Life": "Infinite (dual battery system)",
        "Connectivity": "2.4GHz Wireless, Bluetooth 5.0, USB-C",
        "Microphone": "ClearCast Gen 2 retractable mic",
        "Features": "Active Noise Cancellation, Transparency Mode"
      },
      created_at: "2023-04-05T00:00:00Z",
      updated_at: "2023-09-10T00:00:00Z",
      rating: 4.7,
      review_count: 210,
      reviews: [],
      threads: [],
      upvotes: 365,
      downvotes: 28,
      score: 337,
      rank: 2
    },
    {
      id: "beyerdynamic-mmx300",
      name: "Beyerdynamic MMX 300",
      description: "Premium audiophile-grade wired gaming headset with studio-quality sound",
      category: "headsets",
      price: 299.00,
      url_slug: "beyerdynamic-mmx300",
      image_url: "/images/products/beyerdynamic-mmx300.jpg",
      imageUrl: "/images/products/beyerdynamic-mmx300.jpg",
      specifications: {
        "Drivers": "Dynamic Tesla Neodymium",
        "Frequency Response": "5Hz-35kHz",
        "Impedance": "32 ohms",
        "Connectivity": "3.5mm, 6.35mm adapter included",
        "Microphone": "Cardioid condenser boom mic",
        "Features": "Closed-back design, Velour ear pads, Made in Germany"
      },
      created_at: "2023-02-10T00:00:00Z",
      updated_at: "2023-07-15T00:00:00Z",
      rating: 4.9,
      review_count: 125,
      reviews: [],
      threads: [],
      upvotes: 320,
      downvotes: 10,
      score: 310,
      rank: 3
    },
    {
      id: "sennheiser-pc38x",
      name: "Sennheiser PC38X",
      description: "Open-back gaming headset with exceptional soundstage and comfort",
      category: "headsets",
      price: 169.00,
      url_slug: "sennheiser-pc38x",
      image_url: "/images/products/sennheiser-pc38x.jpg",
      imageUrl: "/images/products/sennheiser-pc38x.jpg",
      specifications: {
        "Drivers": "45mm high-fidelity",
        "Frequency Response": "10Hz-30kHz",
        "Impedance": "28 ohms",
        "Connectivity": "3.5mm split or combo",
        "Microphone": "Noise-cancelling broadcast quality flip-to-mute",
        "Features": "Open-back design, Velour ear pads, Split audio/mic cables"
      },
      created_at: "2023-03-15T00:00:00Z",
      updated_at: "2023-08-20T00:00:00Z",
      rating: 4.8,
      review_count: 220,
      reviews: [],
      threads: [],
      upvotes: 298,
      downvotes: 12,
      score: 286,
      rank: 4
    },
    {
      id: "hyperx-cloud-alpha",
      name: "HyperX Cloud Alpha Wireless",
      description: "Gaming headset with 300-hour battery life and DTS spatial audio",
      category: "headsets",
      price: 199.99,
      url_slug: "hyperx-cloud-alpha-wireless",
      image_url: "/images/products/hyperx-cloud-alpha-wireless.jpg",
      imageUrl: "/images/products/hyperx-cloud-alpha-wireless.jpg",
      specifications: {
        "Drivers": "50mm DTS Headphone:X",
        "Frequency Response": "15Hz-21kHz",
        "Battery Life": "Up to 300 hours",
        "Connectivity": "2.4GHz Wireless",
        "Microphone": "Detachable noise-cancelling",
        "Features": "Dual chamber drivers, Memory foam ear cushions, Aluminum frame"
      },
      created_at: "2023-01-25T00:00:00Z",
      updated_at: "2023-06-30T00:00:00Z",
      rating: 4.7,
      review_count: 245,
      reviews: [],
      threads: [],
      upvotes: 285,
      downvotes: 18,
      score: 267,
      rank: 5
    },
    {
      id: "razer-blackshark-v2-pro",
      name: "Razer BlackShark V2 Pro",
      description: "Wireless esports headset with titanium-coated drivers and HyperSpeed technology",
      category: "headsets",
      price: 179.99,
      url_slug: "razer-blackshark-v2-pro",
      image_url: "/images/products/razer-blackshark-v2-pro.jpg",
      imageUrl: "/images/products/razer-blackshark-v2-pro.jpg",
      specifications: {
        "Drivers": "50mm Titanium-coated diaphragms",
        "Frequency Response": "12Hz-28kHz",
        "Battery Life": "Up to 70 hours",
        "Connectivity": "2.4GHz Wireless, 3.5mm",
        "Microphone": "Razer HyperClear Super Wideband",
        "Features": "THX Spatial Audio, TriForce Titanium drivers, Memory foam cushions"
      },
      created_at: "2023-04-22T00:00:00Z",
      updated_at: "2023-09-15T00:00:00Z",
      rating: 4.6,
      review_count: 198,
      reviews: [],
      threads: [],
      upvotes: 275,
      downvotes: 22,
      score: 253,
      rank: 6
    },
    {
      id: "astro-a50",
      name: "ASTRO Gaming A50 Gen 4",
      description: "Wireless gaming headset with base station and Dolby Audio",
      category: "headsets",
      price: 299.99,
      url_slug: "astro-a50",
      image_url: "/images/products/astro-a50.jpg",
      imageUrl: "/images/products/astro-a50.jpg",
      specifications: {
        "Drivers": "40mm Neodymium Magnet",
        "Frequency Response": "20Hz-20kHz",
        "Battery Life": "Up to 15 hours",
        "Connectivity": "2.4GHz Wireless with base station",
        "Microphone": "Flip-to-mute unidirectional",
        "Features": "Dolby Audio, Base station with charging, Mod Kit ready"
      },
      created_at: "2023-02-05T00:00:00Z",
      updated_at: "2023-07-10T00:00:00Z",
      rating: 4.5,
      review_count: 210,
      reviews: [],
      threads: [],
      upvotes: 260,
      downvotes: 25,
      score: 235,
      rank: 7
    },
    {
      id: "corsair-hs80-rgb",
      name: "Corsair HS80 RGB Wireless",
      description: "Gaming headset with Dolby Atmos and broadcast-grade microphone",
      category: "headsets",
      price: 149.99,
      url_slug: "corsair-hs80-rgb",
      image_url: "/images/products/corsair-hs80-rgb.jpg",
      imageUrl: "/images/products/corsair-hs80-rgb.jpg",
      specifications: {
        "Drivers": "50mm Neodymium",
        "Frequency Response": "20Hz-40kHz",
        "Battery Life": "Up to 20 hours",
        "Connectivity": "SLIPSTREAM WIRELESS, USB",
        "Microphone": "Omnidirectional broadcast-grade",
        "Features": "Dolby Atmos, Floating headband design, Memory foam ear cups"
      },
      created_at: "2023-03-02T00:00:00Z",
      updated_at: "2023-08-05T00:00:00Z",
      rating: 4.6,
      review_count: 175,
      reviews: [],
      threads: [],
      upvotes: 245,
      downvotes: 20,
      score: 225,
      rank: 8
    },
    {
      id: "logitech-g-pro-x",
      name: "Logitech G PRO X Wireless LIGHTSPEED",
      description: "Pro-grade wireless gaming headset with Blue VO!CE microphone technology",
      category: "headsets",
      price: 199.99,
      url_slug: "logitech-g-pro-x-wireless",
      image_url: "/images/products/logitech-g-pro-x-wireless.jpg",
      imageUrl: "/images/products/logitech-g-pro-x-wireless.jpg",
      specifications: {
        "Drivers": "50mm PRO-G",
        "Frequency Response": "20Hz-20kHz",
        "Battery Life": "Up to 20 hours",
        "Connectivity": "LIGHTSPEED Wireless",
        "Microphone": "Blue VO!CE technology",
        "Features": "DTS Headphone:X 2.0, Memory foam earpads, Pro-grade construction"
      },
      created_at: "2023-01-18T00:00:00Z",
      updated_at: "2023-06-22T00:00:00Z",
      rating: 4.7,
      review_count: 190,
      reviews: [],
      threads: [],
      upvotes: 238,
      downvotes: 18,
      score: 220,
      rank: 9
    },
    {
      id: "drop-panda",
      name: "Drop + THX Panda",
      description: "Audiophile wireless headphones with THX AAA amplifier technology",
      category: "headsets",
      price: 399.00,
      url_slug: "drop-panda",
      image_url: "/images/products/drop-panda.jpg",
      imageUrl: "/images/products/drop-panda.jpg",
      specifications: {
        "Drivers": "Planar Ribbon",
        "Frequency Response": "10Hz-50kHz",
        "Battery Life": "Up to 30 hours",
        "Connectivity": "Bluetooth 5.0, USB-C, 3.5mm",
        "Microphone": "Built-in with Qualcomm cVc 8.0",
        "Features": "THX AAA amplifier, Passive mode operation, High-resolution certified"
      },
      created_at: "2023-05-10T00:00:00Z",
      updated_at: "2023-10-15T00:00:00Z",
      rating: 4.8,
      review_count: 120,
      reviews: [],
      threads: [],
      upvotes: 230,
      downvotes: 12,
      score: 218,
      rank: 10
    },
    {
      id: "epos-h3pro-hybrid",
      name: "EPOS H3PRO Hybrid",
      description: "Multi-platform gaming headset with ANC and multiple connectivity options",
      category: "headsets",
      price: 279.00,
      url_slug: "epos-h3pro-hybrid",
      image_url: "/images/products/epos-h3pro-hybrid.jpg",
      imageUrl: "/images/products/epos-h3pro-hybrid.jpg",
      specifications: {
        "Drivers": "Custom-tuned dynamic",
        "Frequency Response": "20Hz-20kHz",
        "Battery Life": "Up to 30 hours",
        "Connectivity": "2.4GHz Wireless, Bluetooth 5.2, 3.5mm",
        "Microphone": "Removable lift-to-mute boom",
        "Features": "Active Noise Cancellation, Smart Button controls"
      },
      created_at: "2023-04-15T00:00:00Z",
      updated_at: "2023-09-20T00:00:00Z",
      rating: 4.6,
      review_count: 135,
      reviews: [],
      threads: [],
      upvotes: 220,
      downvotes: 15,
      score: 205,
      rank: 11
    },
    {
      id: "audio-technica-ath-g1wl",
      name: "Audio-Technica ATH-G1WL",
      description: "Premium wireless gaming headset with studio-quality sound",
      category: "headsets",
      price: 249.00,
      url_slug: "audio-technica-ath-g1wl",
      image_url: "/images/products/audio-technica-ath-g1wl.jpg",
      imageUrl: "/images/products/audio-technica-ath-g1wl.jpg",
      specifications: {
        "Drivers": "45mm large-aperture",
        "Frequency Response": "5Hz-40kHz",
        "Battery Life": "Up to 15 hours",
        "Connectivity": "2.4GHz Wireless",
        "Microphone": "Detachable boom microphone",
        "Features": "Premium Audio-Technica sound quality, Lightweight design"
      },
      created_at: "2023-02-20T00:00:00Z",
      updated_at: "2023-07-25T00:00:00Z",
      rating: 4.5,
      review_count: 95,
      reviews: [],
      threads: [],
      upvotes: 210,
      downvotes: 18,
      score: 192,
      rank: 12
    },
    {
      id: "hifiman-deva-pro",
      name: "HIFIMAN Deva Pro",
      description: "Audiophile open-back planar magnetic headset with Bluetooth module",
      category: "headsets",
      price: 329.00,
      url_slug: "hifiman-deva-pro",
      image_url: "/images/products/hifiman-deva-pro.jpg",
      imageUrl: "/images/products/hifiman-deva-pro.jpg",
      specifications: {
        "Drivers": "Planar Magnetic",
        "Frequency Response": "20Hz-20kHz",
        "Battery Life": "Up to 8 hours (Bluemini)",
        "Connectivity": "Bluetooth 5.0, 3.5mm, Balanced",
        "Microphone": "Built-in on Bluemini R2R module",
        "Features": "Detachable Bluemini module, Open-back design, Audiophile sound"
      },
      created_at: "2023-03-28T00:00:00Z",
      updated_at: "2023-08-30T00:00:00Z",
      rating: 4.7,
      review_count: 75,
      reviews: [],
      threads: [],
      upvotes: 200,
      downvotes: 12,
      score: 188,
      rank: 13
    },
    {
      id: "turtle-beach-stealth-700-gen2",
      name: "Turtle Beach Stealth 700 Gen 2",
      description: "Bluetooth-enabled wireless gaming headset with flip-to-mute mic",
      category: "headsets",
      price: 149.95,
      url_slug: "turtle-beach-stealth-700-gen2",
      image_url: "/images/products/turtle-beach-stealth-700-gen2.jpg",
      imageUrl: "/images/products/turtle-beach-stealth-700-gen2.jpg",
      specifications: {
        "Drivers": "50mm Nanoclear",
        "Frequency Response": "20Hz-22kHz",
        "Battery Life": "Up to 20 hours",
        "Connectivity": "2.4GHz Wireless, Bluetooth",
        "Microphone": "Flip-to-mute",
        "Features": "Superhuman Hearing, ProSpecs glasses relief, Aerofit cooling gel-infused ear cushions"
      },
      created_at: "2023-01-15T00:00:00Z",
      updated_at: "2023-06-12T00:00:00Z",
      rating: 4.4,
      review_count: 185,
      reviews: [],
      threads: [],
      upvotes: 192,
      downvotes: 22,
      score: 170,
      rank: 14
    },
    {
      id: "alienware-tri-mode-wireless",
      name: "Alienware Tri-Mode Wireless Gaming Headset",
      description: "Premium gaming headset with Dolby Atmos spatial audio and three connectivity modes",
      category: "headsets",
      price: 199.99,
      url_slug: "alienware-tri-mode-wireless",
      image_url: "/images/products/alienware-tri-mode-wireless.jpg",
      imageUrl: "/images/products/alienware-tri-mode-wireless.jpg",
      specifications: {
        "Drivers": "40mm Hi-Res certified",
        "Frequency Response": "20Hz-40kHz",
        "Battery Life": "Up to 30 hours",
        "Connectivity": "2.4GHz Wireless, Bluetooth 5.2, 3.5mm",
        "Microphone": "Detachable boom with AI noise-cancellation",
        "Features": "Active noise cancellation, RGB lighting, Comfort memory foam earcups"
      },
      created_at: "2023-05-05T00:00:00Z",
      updated_at: "2023-10-10T00:00:00Z",
      rating: 4.5,
      review_count: 85,
      reviews: [],
      threads: [],
      upvotes: 180,
      downvotes: 15,
      score: 165,
      rank: 15
    },
    {
      id: "asus-rog-delta-s",
      name: "ASUS ROG Delta S",
      description: "Gaming headset with MQA renderer and quad DAC technology",
      category: "headsets",
      price: 199.99,
      url_slug: "asus-rog-delta-s",
      image_url: "/images/products/asus-rog-delta-s.jpg",
      imageUrl: "/images/products/asus-rog-delta-s.jpg",
      specifications: {
        "Drivers": "50mm ASUS Essence with neodymium magnets",
        "Frequency Response": "20Hz-40kHz",
        "Impedance": "32 ohms",
        "Connectivity": "USB-C, USB-A adapter",
        "Microphone": "AI Noise-Cancelling",
        "Features": "ESS 9281 Quad DAC, MQA Renderer, RGB lighting"
      },
      created_at: "2023-02-08T00:00:00Z",
      updated_at: "2023-07-15T00:00:00Z",
      rating: 4.5,
      review_count: 110,
      reviews: [],
      threads: [],
      upvotes: 176,
      downvotes: 16,
      score: 160,
      rank: 16
    },
    {
      id: "meze-99-neo",
      name: "Meze 99 Neo",
      description: "Audiophile closed-back headphones with detachable cables and high resolution sound",
      category: "headsets",
      price: 199.00,
      url_slug: "meze-99-neo",
      image_url: "/images/products/meze-99-neo.jpg",
      imageUrl: "/images/products/meze-99-neo.jpg",
      specifications: {
        "Drivers": "40mm dynamic",
        "Frequency Response": "15Hz-25kHz",
        "Impedance": "26 ohms",
        "Connectivity": "Detachable cables (1.2m + 3m)",
        "Microphone": "Optional inline mic cable available",
        "Features": "Memory foam ear pads, Lightweight self-adjusting headband"
      },
      created_at: "2023-04-10T00:00:00Z",
      updated_at: "2023-09-05T00:00:00Z",
      rating: 4.7,
      review_count: 65,
      reviews: [],
      threads: [],
      upvotes: 168,
      downvotes: 8,
      score: 160,
      rank: 17
    },
    {
      id: "philips-shp9500",
      name: "Philips SHP9500",
      description: "Audiophile open-back headphones with exceptional value and comfort",
      category: "headsets",
      price: 74.99,
      url_slug: "philips-shp9500",
      image_url: "/images/products/philips-shp9500.jpg",
      imageUrl: "/images/products/philips-shp9500.jpg",
      specifications: {
        "Drivers": "50mm neodymium",
        "Frequency Response": "12Hz-35kHz",
        "Impedance": "32 ohms",
        "Connectivity": "3.5mm with 6.3mm adapter",
        "Microphone": "Compatible with V-MODA BoomPro (sold separately)",
        "Features": "Open-back design, Breathable ear pads, Lightweight construction"
      },
      created_at: "2023-01-20T00:00:00Z",
      updated_at: "2023-06-25T00:00:00Z",
      rating: 4.6,
      review_count: 320,
      reviews: [],
      threads: [],
      upvotes: 152,
      downvotes: 12,
      score: 140,
      rank: 18
    },
    {
      id: "jbl-quantum-910",
      name: "JBL Quantum 910 Wireless",
      description: "Gaming headset with head-tracking spatial audio and active noise cancellation",
      category: "headsets",
      price: 249.95,
      url_slug: "jbl-quantum-910",
      image_url: "/images/products/jbl-quantum-910.jpg",
      imageUrl: "/images/products/jbl-quantum-910.jpg",
      specifications: {
        "Drivers": "50mm JBL QuantumSOUND Signature",
        "Frequency Response": "20Hz-20kHz",
        "Battery Life": "Up to 39 hours",
        "Connectivity": "2.4GHz Wireless, Bluetooth 5.2, 3.5mm",
        "Microphone": "Detachable boom with echo and noise suppression",
        "Features": "Head-tracked spatial audio, Active noise cancellation, Dual wireless"
      },
      created_at: "2023-03-15T00:00:00Z",
      updated_at: "2023-08-12T00:00:00Z",
      rating: 4.4,
      review_count: 130,
      reviews: [],
      threads: [],
      upvotes: 145,
      downvotes: 18,
      score: 127,
      rank: 19
    },
    {
      id: "lucidsound-ls50x",
      name: "LucidSound LS50X",
      description: "Premium wireless gaming headset with cooling gel-infused earpads",
      category: "headsets",
      price: 249.99,
      url_slug: "lucidsound-ls50x",
      image_url: "/images/products/lucidsound-ls50x.jpg",
      imageUrl: "/images/products/lucidsound-ls50x.jpg",
      specifications: {
        "Drivers": "50mm custom-tuned",
        "Frequency Response": "20Hz-20kHz",
        "Battery Life": "Up to 20 hours",
        "Connectivity": "2.4GHz Wireless, Bluetooth",
        "Microphone": "Dual mic system with removable boom",
        "Features": "Gel-cooled memory foam earpads, Quick-access controls, Travel case included"
      },
      created_at: "2023-02-28T00:00:00Z",
      updated_at: "2023-07-30T00:00:00Z",
      rating: 4.3,
      review_count: 95,
      reviews: [],
      threads: [],
      upvotes: 135,
      downvotes: 15,
      score: 120,
      rank: 20
    }
  ];
} 