import { Product } from "@/types/product";
import { v4 as uuidv4 } from 'uuid';

/**
 * Generates additional keyboard products for the expanded catalog
 * @returns Array of keyboard products
 */
export function generateAdditionalKeyboards(): Product[] {
  return [
    {
      id: "wooting-60he",
      name: "Wooting 60HE",
      description: "Compact analog mechanical gaming keyboard with rapid trigger technology",
      category: "keyboards",
      price: 174.99,
      url_slug: "wooting-60he",
      image_url: "/images/products/wooting-60he.jpg",
      imageUrl: "/images/products/wooting-60he.jpg",
      specifications: {
        "Switches": "Lekker (Hall Effect)",
        "Keycaps": "PBT",
        "Layout": "60%",
        "Actuation": "0.1mm to 4.0mm (adjustable)",
        "Connectivity": "USB-C",
        "Features": "Analog input, Rapid trigger, RGB lighting"
      },
      created_at: "2023-03-10T00:00:00Z",
      updated_at: "2023-08-15T00:00:00Z",
      rating: 4.9,
      review_count: 125,
      reviews: [],
      threads: [],
      upvotes: 350,
      downvotes: 18,
      score: 332,
      rank: 1
    },
    {
      id: "keychron-q1-pro",
      name: "Keychron Q1 Pro",
      description: "Wireless mechanical keyboard with QMK/VIA compatibility and aluminum frame",
      category: "keyboards",
      price: 199.99,
      url_slug: "keychron-q1-pro",
      image_url: "/images/products/keychron-q1-pro.jpg",
      imageUrl: "/images/products/keychron-q1-pro.jpg",
      specifications: {
        "Switches": "Gateron G Pro (Red, Blue, Brown)",
        "Keycaps": "Double-shot PBT",
        "Layout": "75%",
        "Connectivity": "Bluetooth 5.1, USB-C",
        "Battery": "4000mAh",
        "Features": "Hot-swappable, Gasket mount, QMK/VIA programmable"
      },
      created_at: "2023-04-15T00:00:00Z",
      updated_at: "2023-09-20T00:00:00Z",
      rating: 4.8,
      review_count: 165,
      reviews: [],
      threads: [],
      upvotes: 410,
      downvotes: 25,
      score: 385,
      rank: 2
    },
    {
      id: "gmmk-pro",
      name: "Glorious GMMK Pro",
      description: "Customizable 75% gasket-mounted mechanical keyboard with rotary encoder",
      category: "keyboards",
      price: 169.99,
      url_slug: "gmmk-pro",
      image_url: "/images/products/gmmk-pro.jpg",
      imageUrl: "/images/products/gmmk-pro.jpg",
      specifications: {
        "Switches": "Hot-swappable",
        "Keycaps": "Not included",
        "Layout": "75%",
        "Connectivity": "USB-C",
        "Features": "Rotary encoder, Gasket mount, RGB lighting, Aluminum frame"
      },
      created_at: "2023-01-22T00:00:00Z",
      updated_at: "2023-07-14T00:00:00Z",
      rating: 4.7,
      review_count: 203,
      reviews: [],
      threads: [],
      upvotes: 328,
      downvotes: 22,
      score: 306,
      rank: 3
    },
    {
      id: "ducky-one-3",
      name: "Ducky One 3",
      description: "Premium mechanical keyboard with hot-swap capability and double-shot PBT keycaps",
      category: "keyboards",
      price: 129.99,
      url_slug: "ducky-one-3",
      image_url: "/images/products/ducky-one-3.jpg",
      imageUrl: "/images/products/ducky-one-3.jpg",
      specifications: {
        "Switches": "Cherry MX (multiple options)",
        "Keycaps": "Double-shot PBT",
        "Layout": "Full-size / TKL / 60% (Multiple options)",
        "Connectivity": "USB-C",
        "Features": "Hot-swappable, Dual-layer PCB, RGB lighting"
      },
      created_at: "2023-02-05T00:00:00Z",
      updated_at: "2023-06-30T00:00:00Z",
      rating: 4.8,
      review_count: 178,
      reviews: [],
      threads: [],
      upvotes: 320,
      downvotes: 15,
      score: 305,
      rank: 4
    },
    {
      id: "razer-huntsman-v2",
      name: "Razer Huntsman V2",
      description: "Gaming keyboard with optical switches and sound dampening foam",
      category: "keyboards",
      price: 189.99,
      url_slug: "razer-huntsman-v2",
      image_url: "/images/products/razer-huntsman-v2.jpg",
      imageUrl: "/images/products/razer-huntsman-v2.jpg",
      specifications: {
        "Switches": "Razer Optical Gen-2 (Linear/Clicky)",
        "Keycaps": "Doubleshot PBT",
        "Layout": "Full-size",
        "Connectivity": "USB-C",
        "Features": "8000Hz polling rate, Sound dampening foam, Multi-function digital dial"
      },
      created_at: "2023-01-15T00:00:00Z",
      updated_at: "2023-05-22T00:00:00Z",
      rating: 4.6,
      review_count: 245,
      reviews: [],
      threads: [],
      upvotes: 292,
      downvotes: 28,
      score: 264,
      rank: 5
    },
    {
      id: "nk65-entry",
      name: "NovelKeys NK65 Entry Edition",
      description: "Budget-friendly 65% hot-swappable mechanical keyboard",
      category: "keyboards",
      price: 95.00,
      url_slug: "nk65-entry",
      image_url: "/images/products/nk65-entry.jpg",
      imageUrl: "/images/products/nk65-entry.jpg",
      specifications: {
        "Switches": "Hot-swappable",
        "Keycaps": "Not included",
        "Layout": "65%",
        "Connectivity": "USB-C",
        "Features": "Polycarbonate case, RGB lighting, Screw-in stabilizers"
      },
      created_at: "2023-03-18T00:00:00Z",
      updated_at: "2023-08-05T00:00:00Z",
      rating: 4.7,
      review_count: 156,
      reviews: [],
      threads: [],
      upvotes: 285,
      downvotes: 22,
      score: 263,
      rank: 6
    },
    {
      id: "logitech-g915-tkl",
      name: "Logitech G915 TKL",
      description: "Low-profile wireless gaming keyboard with mechanical switches",
      category: "keyboards",
      price: 229.99,
      url_slug: "logitech-g915-tkl",
      image_url: "/images/products/logitech-g915-tkl.jpg",
      imageUrl: "/images/products/logitech-g915-tkl.jpg",
      specifications: {
        "Switches": "GL Low Profile (Tactile/Linear/Clicky)",
        "Keycaps": "Low profile",
        "Layout": "Tenkeyless",
        "Connectivity": "LIGHTSPEED Wireless, Bluetooth, USB-C",
        "Battery": "Up to 40 hours",
        "Features": "Dedicated media controls, Aluminum alloy construction"
      },
      created_at: "2023-02-12T00:00:00Z",
      updated_at: "2023-07-25T00:00:00Z",
      rating: 4.5,
      review_count: 210,
      reviews: [],
      threads: [],
      upvotes: 275,
      downvotes: 30,
      score: 245,
      rank: 7
    },
    {
      id: "akko-mod-007",
      name: "Akko MOD 007",
      description: "Gasket-mounted enthusiast mechanical keyboard with CNC aluminum case",
      category: "keyboards",
      price: 159.99,
      url_slug: "akko-mod-007",
      image_url: "/images/products/akko-mod-007.jpg",
      imageUrl: "/images/products/akko-mod-007.jpg",
      specifications: {
        "Switches": "Akko CS (Multiple options) / Hot-swappable",
        "Keycaps": "Double-shot PBT (Optional)",
        "Layout": "75%",
        "Connectivity": "USB-C",
        "Features": "Gasket mount, PC plate, Silicone dampening, South-facing RGB"
      },
      created_at: "2023-04-02T00:00:00Z",
      updated_at: "2023-09-10T00:00:00Z",
      rating: 4.7,
      review_count: 132,
      reviews: [],
      threads: [],
      upvotes: 265,
      downvotes: 22,
      score: 243,
      rank: 8
    },
    {
      id: "drop-ctrl",
      name: "Drop CTRL",
      description: "Premium TKL mechanical keyboard with hot-swappable switches and per-key RGB",
      category: "keyboards",
      price: 189.99,
      url_slug: "drop-ctrl",
      image_url: "/images/products/drop-ctrl.jpg",
      imageUrl: "/images/products/drop-ctrl.jpg",
      specifications: {
        "Switches": "Hot-swappable (Cherry MX, Kaihua, Halo)",
        "Keycaps": "Doubleshot PBT",
        "Layout": "Tenkeyless",
        "Connectivity": "USB-C",
        "Features": "CNC aluminum frame, Per-key RGB, Dual USB-C ports"
      },
      created_at: "2023-01-30T00:00:00Z",
      updated_at: "2023-06-20T00:00:00Z",
      rating: 4.6,
      review_count: 185,
      reviews: [],
      threads: [],
      upvotes: 252,
      downvotes: 28,
      score: 224,
      rank: 9
    },
    {
      id: "nuphy-air75",
      name: "NuPhy Air75",
      description: "Ultra-thin wireless mechanical keyboard with low-profile switches",
      category: "keyboards",
      price: 129.95,
      url_slug: "nuphy-air75",
      image_url: "/images/products/nuphy-air75.jpg",
      imageUrl: "/images/products/nuphy-air75.jpg",
      specifications: {
        "Switches": "Gateron Low Profile (Red/Blue/Brown)",
        "Keycaps": "PBT spherical",
        "Layout": "75%",
        "Connectivity": "2.4GHz Wireless, Bluetooth 5.0, USB-C",
        "Battery": "4000mAh",
        "Features": "Ultra-thin design (16mm), RGB backlight, Compatible with Mac & Windows"
      },
      created_at: "2023-03-25T00:00:00Z",
      updated_at: "2023-08-19T00:00:00Z",
      rating: 4.7,
      review_count: 142,
      reviews: [],
      threads: [],
      upvotes: 238,
      downvotes: 18,
      score: 220,
      rank: 10
    },
    {
      id: "kbd67-lite",
      name: "KBDfans KBD67 Lite",
      description: "Budget-friendly 65% gasket-mounted keyboard kit",
      category: "keyboards",
      price: 109.00,
      url_slug: "kbd67-lite",
      image_url: "/images/products/kbd67-lite.jpg",
      imageUrl: "/images/products/kbd67-lite.jpg",
      specifications: {
        "Switches": "Hot-swappable",
        "Keycaps": "Not included",
        "Layout": "65%",
        "Connectivity": "USB-C",
        "Features": "Gasket mount, Silicone dampening, Polycarbonate plate"
      },
      created_at: "2023-02-28T00:00:00Z",
      updated_at: "2023-07-10T00:00:00Z",
      rating: 4.8,
      review_count: 115,
      reviews: [],
      threads: [],
      upvotes: 225,
      downvotes: 15,
      score: 210,
      rank: 11
    },
    {
      id: "epomaker-th80",
      name: "Epomaker TH80",
      description: "75% tri-mode wireless mechanical keyboard with knob",
      category: "keyboards",
      price: 99.99,
      url_slug: "epomaker-th80",
      image_url: "/images/products/epomaker-th80.jpg",
      imageUrl: "/images/products/epomaker-th80.jpg",
      specifications: {
        "Switches": "Gateron Pro (multiple options)",
        "Keycaps": "PBT",
        "Layout": "75% with knob",
        "Connectivity": "2.4GHz Wireless, Bluetooth 5.0, USB-C",
        "Battery": "3000mAh",
        "Features": "Hot-swappable, RGB lighting, Rotary knob, Silicone dampening"
      },
      created_at: "2023-04-10T00:00:00Z",
      updated_at: "2023-09-02T00:00:00Z",
      rating: 4.5,
      review_count: 128,
      reviews: [],
      threads: [],
      upvotes: 218,
      downvotes: 22,
      score: 196,
      rank: 12
    },
    {
      id: "asus-rog-azoth",
      name: "ASUS ROG Azoth",
      description: "Premium 75% wireless gaming keyboard with OLED display and tri-layer dampening",
      category: "keyboards",
      price: 249.99,
      url_slug: "asus-rog-azoth",
      image_url: "/images/products/asus-rog-azoth.jpg",
      imageUrl: "/images/products/asus-rog-azoth.jpg",
      specifications: {
        "Switches": "ROG NX (Red/Blue/Brown)",
        "Keycaps": "PBT doubleshot",
        "Layout": "75% with knob",
        "Connectivity": "2.4GHz Wireless, Bluetooth, USB-C",
        "Battery": "Up to 2000 hours",
        "Features": "OLED display, Tri-layer dampening, Pre-lubed switches, Hot-swappable"
      },
      created_at: "2023-01-05T00:00:00Z",
      updated_at: "2023-06-12T00:00:00Z",
      rating: 4.7,
      review_count: 95,
      reviews: [],
      threads: [],
      upvotes: 210,
      downvotes: 18,
      score: 192,
      rank: 13
    },
    {
      id: "mountain-everest-max",
      name: "Mountain Everest Max",
      description: "Modular mechanical keyboard with detachable numpad and media dock",
      category: "keyboards",
      price: 149.99,
      url_slug: "mountain-everest-max",
      image_url: "/images/products/mountain-everest-max.jpg",
      imageUrl: "/images/products/mountain-everest-max.jpg",
      specifications: {
        "Switches": "Cherry MX (multiple options)",
        "Keycaps": "Double-shot PBT",
        "Layout": "Modular (TKL base + detachable numpad)",
        "Connectivity": "USB-C",
        "Features": "Detachable media dock, Modular numpad (left/right), Display Dial"
      },
      created_at: "2023-03-05T00:00:00Z",
      updated_at: "2023-08-08T00:00:00Z",
      rating: 4.6,
      review_count: 82,
      reviews: [],
      threads: [],
      upvotes: 200,
      downvotes: 15,
      score: 185,
      rank: 14
    },
    {
      id: "varmilo-ma87m",
      name: "Varmilo MA87M",
      description: "High-quality TKL mechanical keyboard with dye-sublimated PBT keycaps",
      category: "keyboards",
      price: 139.00,
      url_slug: "varmilo-ma87m",
      image_url: "/images/products/varmilo-ma87m.jpg",
      imageUrl: "/images/products/varmilo-ma87m.jpg",
      specifications: {
        "Switches": "Cherry MX / EC V2 (multiple options)",
        "Keycaps": "Dye-sublimated PBT",
        "Layout": "Tenkeyless",
        "Connectivity": "USB-C",
        "Features": "Various design themes, Steel plate, Premium construction"
      },
      created_at: "2023-02-15T00:00:00Z",
      updated_at: "2023-07-18T00:00:00Z",
      rating: 4.7,
      review_count: 98,
      reviews: [],
      threads: [],
      upvotes: 195,
      downvotes: 12,
      score: 183,
      rank: 15
    },
    {
      id: "corsair-k100-rgb",
      name: "Corsair K100 RGB",
      description: "Premium gaming keyboard with OPX optical-mechanical switches and iCUE control wheel",
      category: "keyboards",
      price: 229.99,
      url_slug: "corsair-k100-rgb",
      image_url: "/images/products/corsair-k100-rgb.jpg",
      imageUrl: "/images/products/corsair-k100-rgb.jpg",
      specifications: {
        "Switches": "Corsair OPX Optical-Mechanical / Cherry MX Speed",
        "Keycaps": "PBT double-shot",
        "Layout": "Full-size",
        "Connectivity": "USB-A (2x)",
        "Features": "4000Hz polling rate, iCUE control wheel, Per-key RGB, 8MB onboard storage"
      },
      created_at: "2023-01-20T00:00:00Z",
      updated_at: "2023-05-15T00:00:00Z",
      rating: 4.5,
      review_count: 175,
      reviews: [],
      threads: [],
      upvotes: 188,
      downvotes: 22,
      score: 166,
      rank: 16
    },
    {
      id: "fnatic-streak65-lp",
      name: "Fnatic Streak65 LP",
      description: "Low-profile 65% gaming keyboard designed for esports",
      category: "keyboards",
      price: 109.99,
      url_slug: "fnatic-streak65-lp",
      image_url: "/images/products/fnatic-streak65-lp.jpg",
      imageUrl: "/images/products/fnatic-streak65-lp.jpg",
      specifications: {
        "Switches": "Low Profile Fnatic Speed Silver",
        "Keycaps": "PBT",
        "Layout": "65%",
        "Connectivity": "USB-C",
        "Features": "Full metal plate, Sound dampening foam, Competition Mode"
      },
      created_at: "2023-04-05T00:00:00Z",
      updated_at: "2023-09-15T00:00:00Z",
      rating: 4.5,
      review_count: 86,
      reviews: [],
      threads: [],
      upvotes: 175,
      downvotes: 15,
      score: 160,
      rank: 17
    },
    {
      id: "mistel-md770",
      name: "Mistel MD770",
      description: "Split ergonomic mechanical keyboard with RGB backlighting",
      category: "keyboards",
      price: 119.00,
      url_slug: "mistel-md770",
      image_url: "/images/products/mistel-md770.jpg",
      imageUrl: "/images/products/mistel-md770.jpg",
      specifications: {
        "Switches": "Cherry MX (multiple options)",
        "Keycaps": "PBT double-shot",
        "Layout": "Split TKL",
        "Connectivity": "USB-C",
        "Features": "Ergonomic split design, Programmable, RGB backlighting"
      },
      created_at: "2023-03-12T00:00:00Z",
      updated_at: "2023-08-22T00:00:00Z",
      rating: 4.6,
      review_count: 68,
      reviews: [],
      threads: [],
      upvotes: 168,
      downvotes: 12,
      score: 156,
      rank: 18
    },
    {
      id: "royal-kludge-rk84",
      name: "Royal Kludge RK84",
      description: "Budget-friendly 75% triple-mode wireless mechanical keyboard",
      category: "keyboards",
      price: 79.99,
      url_slug: "royal-kludge-rk84",
      image_url: "/images/products/royal-kludge-rk84.jpg",
      imageUrl: "/images/products/royal-kludge-rk84.jpg",
      specifications: {
        "Switches": "RK (Red/Blue/Brown)",
        "Keycaps": "ABS double-shot",
        "Layout": "75%",
        "Connectivity": "2.4GHz Wireless, Bluetooth 5.0, USB-C",
        "Battery": "3750mAh",
        "Features": "Hot-swappable, RGB backlight, Windows/Mac compatible"
      },
      created_at: "2023-02-25T00:00:00Z",
      updated_at: "2023-07-20T00:00:00Z",
      rating: 4.4,
      review_count: 245,
      reviews: [],
      threads: [],
      upvotes: 160,
      downvotes: 25,
      score: 135,
      rank: 19
    },
    {
      id: "cooler-master-mm712",
      name: "Cooler Master MM712",
      description: "Unique gaming keyboard with modular magnetic top plate",
      category: "keyboards",
      price: 159.99,
      url_slug: "cooler-master-mm712",
      image_url: "/images/products/cooler-master-mm712.jpg",
      imageUrl: "/images/products/cooler-master-mm712.jpg",
      specifications: {
        "Switches": "Cherry MX (Red/Blue/Brown)",
        "Keycaps": "PBT double-shot",
        "Layout": "Full-size",
        "Connectivity": "USB-C",
        "Features": "Swappable magnetic top plate, Per-key RGB, Multiple accent colors"
      },
      created_at: "2023-03-30T00:00:00Z",
      updated_at: "2023-08-25T00:00:00Z",
      rating: 4.3,
      review_count: 112,
      reviews: [],
      threads: [],
      upvotes: 145,
      downvotes: 22,
      score: 123,
      rank: 20
    }
  ];
} 