import { Product } from "@/types/product";
import { v4 as uuidv4 } from 'uuid';

/**
 * Generate additional gaming mice products to expand the database
 */
export function generateAdditionalMice(): Product[] {
  return [
    {
      id: uuidv4(),
      name: "Razer DeathAdder V3 Pro",
      description: "Lightweight wireless gaming mouse with Focus Pro 30K sensor and ergonomic design",
      category: "mice",
      price: 149.99,
      url_slug: "razer-deathadder-v3-pro",
      image_url: "/images/products/deathadder-v3-pro.jpg",
      imageUrl: "/images/products/deathadder-v3-pro.jpg",
      specifications: {
        "Sensor": "Focus Pro 30K",
        "DPI Range": "100-30,000",
        "Weight": "63g",
        "Battery Life": "Up to 90 hours",
        "Connectivity": "HyperSpeed Wireless",
        "Buttons": "5 Programmable Buttons"
      },
      created_at: "2023-05-10T00:00:00Z",
      updated_at: "2023-10-15T00:00:00Z",
      rating: 4.9,
      review_count: 230,
      reviews: [],
      threads: [],
      upvotes: 452,
      downvotes: 23,
      score: 429,
      rank: 1
    },
    {
      id: uuidv4(),
      name: "Logitech G303 Shroud Edition",
      description: "Lightweight wireless gaming mouse designed in collaboration with Shroud",
      category: "mice",
      price: 129.99,
      url_slug: "logitech-g303-shroud",
      image_url: "/images/products/g303-shroud.jpg",
      imageUrl: "/images/products/g303-shroud.jpg",
      specifications: {
        "Sensor": "HERO 25K",
        "DPI Range": "100-25,600",
        "Weight": "75g",
        "Battery Life": "Up to 70 hours",
        "Connectivity": "LIGHTSPEED Wireless",
        "Buttons": "6 Programmable Buttons"
      },
      created_at: "2023-03-22T00:00:00Z",
      updated_at: "2023-08-18T00:00:00Z",
      rating: 4.7,
      review_count: 185,
      reviews: [],
      threads: [],
      upvotes: 378,
      downvotes: 42,
      score: 336,
      rank: 2
    },
    {
      id: uuidv4(),
      name: "Pulsar X2 Mini",
      description: "Ultra-lightweight symmetrical gaming mouse with 26K sensor",
      category: "mice",
      price: 94.99,
      url_slug: "pulsar-x2-mini",
      image_url: "/images/products/pulsar-x2-mini.jpg",
      imageUrl: "/images/products/pulsar-x2-mini.jpg",
      specifications: {
        "Sensor": "PAW3395 26K",
        "DPI Range": "50-26,000",
        "Weight": "52g",
        "Battery Life": "Up to 70 hours",
        "Connectivity": "2.4GHz Wireless",
        "Buttons": "5 Programmable Buttons"
      },
      created_at: "2023-04-15T00:00:00Z",
      updated_at: "2023-09-20T00:00:00Z",
      rating: 4.8,
      review_count: 142,
      reviews: [],
      threads: [],
      upvotes: 315,
      downvotes: 18,
      score: 297,
      rank: 3
    },
    {
      id: uuidv4(),
      name: "Endgame Gear XM1r",
      description: "Ultra-responsive wired gaming mouse with patented analogue switch technology",
      category: "mice",
      price: 59.99,
      url_slug: "endgame-gear-xm1r",
      image_url: "/images/products/endgame-xm1r.jpg",
      imageUrl: "/images/products/endgame-xm1r.jpg",
      specifications: {
        "Sensor": "PixArt PAW3370",
        "DPI Range": "50-19,000",
        "Weight": "70g",
        "Cable": "Flexible Paracord",
        "Connectivity": "Wired",
        "Buttons": "5 Buttons"
      },
      created_at: "2023-02-08T00:00:00Z",
      updated_at: "2023-07-15T00:00:00Z",
      rating: 4.6,
      review_count: 168,
      reviews: [],
      threads: [],
      upvotes: 286,
      downvotes: 31,
      score: 255,
      rank: 4
    },
    {
      id: uuidv4(),
      name: "Xtrfy M42 RGB",
      description: "Lightweight gaming mouse with swappable shells for different grip styles",
      category: "mice",
      price: 59.99,
      url_slug: "xtrfy-m42-rgb",
      image_url: "/images/products/xtrfy-m42.jpg",
      imageUrl: "/images/products/xtrfy-m42.jpg",
      specifications: {
        "Sensor": "Pixart PMW3389",
        "DPI Range": "400-16,000",
        "Weight": "59g",
        "Cable": "EZcord Flex",
        "Connectivity": "Wired",
        "Buttons": "6 Programmable Buttons"
      },
      created_at: "2023-01-20T00:00:00Z",
      updated_at: "2023-06-30T00:00:00Z",
      rating: 4.5,
      review_count: 154,
      reviews: [],
      threads: [],
      upvotes: 245,
      downvotes: 28,
      score: 217,
      rank: 5
    },
    {
      id: uuidv4(),
      name: "SteelSeries Aerox 3 Wireless",
      description: "Ultra-lightweight wireless gaming mouse with honeycomb design",
      category: "mice",
      price: 99.99,
      url_slug: "steelseries-aerox-3-wireless",
      image_url: "/images/products/aerox-3.jpg",
      imageUrl: "/images/products/aerox-3.jpg",
      specifications: {
        "Sensor": "TrueMove Air",
        "DPI Range": "100-18,000",
        "Weight": "66g",
        "Battery Life": "Up to 200 hours",
        "Connectivity": "2.4GHz & Bluetooth",
        "Buttons": "6 Programmable Buttons"
      },
      created_at: "2023-03-10T00:00:00Z",
      updated_at: "2023-08-08T00:00:00Z",
      rating: 4.4,
      review_count: 178,
      reviews: [],
      threads: [],
      upvotes: 230,
      downvotes: 45,
      score: 185,
      rank: 6
    },
    {
      id: uuidv4(),
      name: "ASUS ROG Keris Wireless",
      description: "Lightweight FPS gaming mouse with hot-swappable switches",
      category: "mice",
      price: 89.99,
      url_slug: "asus-rog-keris-wireless",
      image_url: "/images/products/rog-keris.jpg",
      imageUrl: "/images/products/rog-keris.jpg",
      specifications: {
        "Sensor": "PixArt PAW3335",
        "DPI Range": "100-16,000",
        "Weight": "79g",
        "Battery Life": "Up to 78 hours",
        "Connectivity": "2.4GHz, Bluetooth & Wired",
        "Buttons": "5 Programmable Buttons"
      },
      created_at: "2023-04-05T00:00:00Z",
      updated_at: "2023-09-12T00:00:00Z",
      rating: 4.5,
      review_count: 132,
      reviews: [],
      threads: [],
      upvotes: 214,
      downvotes: 32,
      score: 182,
      rank: 7
    },
    {
      id: uuidv4(),
      name: "Ninjutso Origin One X",
      description: "Lightweight wireless gaming mouse with minimalist design",
      category: "mice",
      price: 79.99,
      url_slug: "ninjutso-origin-one-x",
      image_url: "/images/products/ninjutso-origin.jpg",
      imageUrl: "/images/products/ninjutso-origin.jpg",
      specifications: {
        "Sensor": "PixArt PAW3370",
        "DPI Range": "50-19,000",
        "Weight": "69g",
        "Battery Life": "Up to 70 hours",
        "Connectivity": "2.4GHz Wireless",
        "Buttons": "5 Buttons"
      },
      created_at: "2023-05-18T00:00:00Z",
      updated_at: "2023-10-25T00:00:00Z",
      rating: 4.6,
      review_count: 105,
      reviews: [],
      threads: [],
      upvotes: 195,
      downvotes: 22,
      score: 173,
      rank: 8
    },
    {
      id: uuidv4(),
      name: "HyperX Pulsefire Haste Wireless",
      description: "Ultra-lightweight wireless gaming mouse with honeycomb shell",
      category: "mice",
      price: 79.99,
      url_slug: "hyperx-pulsefire-haste-wireless",
      image_url: "/images/products/pulsefire-haste.jpg",
      imageUrl: "/images/products/pulsefire-haste.jpg",
      specifications: {
        "Sensor": "PAW3335",
        "DPI Range": "400-16,000",
        "Weight": "62g",
        "Battery Life": "Up to 100 hours",
        "Connectivity": "2.4GHz Wireless",
        "Buttons": "6 Programmable Buttons"
      },
      created_at: "2023-03-25T00:00:00Z",
      updated_at: "2023-08-20T00:00:00Z",
      rating: 4.7,
      review_count: 148,
      reviews: [],
      threads: [],
      upvotes: 187,
      downvotes: 19,
      score: 168,
      rank: 9
    },
    {
      id: uuidv4(),
      name: "Vaxee ZYGEN NP-01",
      description: "Ergonomic gaming mouse designed for competitive players",
      category: "mice",
      price: 69.99,
      url_slug: "vaxee-zygen-np-01",
      image_url: "/images/products/vaxee-np01.jpg",
      imageUrl: "/images/products/vaxee-np01.jpg",
      specifications: {
        "Sensor": "PixArt 3389",
        "DPI Range": "400-3200",
        "Weight": "75g",
        "Cable": "Low-Drag Flexible Cable",
        "Connectivity": "Wired",
        "Buttons": "5 Buttons"
      },
      created_at: "2023-02-15T00:00:00Z",
      updated_at: "2023-07-22T00:00:00Z",
      rating: 4.5,
      review_count: 125,
      reviews: [],
      threads: [],
      upvotes: 176,
      downvotes: 32,
      score: 144,
      rank: 10
    },
    {
      id: uuidv4(),
      name: "Mountain Makalu 67",
      description: "Lightweight gaming mouse with PixArt sensor and ribcage design",
      category: "mice",
      price: 59.99,
      url_slug: "mountain-makalu-67",
      image_url: "/images/products/mountain-makalu.jpg",
      imageUrl: "/images/products/mountain-makalu.jpg",
      specifications: {
        "Sensor": "PixArt PAW3370",
        "DPI Range": "100-19,000",
        "Weight": "67g",
        "Cable": "Low-Drag Flexible Cable",
        "Connectivity": "Wired",
        "Buttons": "6 Programmable Buttons"
      },
      created_at: "2023-01-28T00:00:00Z",
      updated_at: "2023-06-15T00:00:00Z",
      rating: 4.4,
      review_count: 98,
      reviews: [],
      threads: [],
      upvotes: 155,
      downvotes: 28,
      score: 127,
      rank: 11
    },
    {
      id: uuidv4(),
      name: "G-Wolves Hati S Ace",
      description: "Ultra-lightweight wireless gaming mouse with classic shape",
      category: "mice",
      price: 119.99,
      url_slug: "g-wolves-hati-s-ace",
      image_url: "/images/products/gwolves-hati.jpg",
      imageUrl: "/images/products/gwolves-hati.jpg",
      specifications: {
        "Sensor": "PixArt PAW3370",
        "DPI Range": "50-19,000",
        "Weight": "55g",
        "Battery Life": "Up to 80 hours",
        "Connectivity": "2.4GHz Wireless",
        "Buttons": "6 Programmable Buttons"
      },
      created_at: "2023-04-28T00:00:00Z",
      updated_at: "2023-09-30T00:00:00Z",
      rating: 4.5,
      review_count: 82,
      reviews: [],
      threads: [],
      upvotes: 142,
      downvotes: 18,
      score: 124,
      rank: 12
    },
    {
      id: uuidv4(),
      name: "Cooler Master MM731",
      description: "Lightweight hybrid wireless gaming mouse",
      category: "mice",
      price: 89.99,
      url_slug: "cooler-master-mm731",
      image_url: "/images/products/mm731.jpg",
      imageUrl: "/images/products/mm731.jpg",
      specifications: {
        "Sensor": "PixArt PAW3370",
        "DPI Range": "100-19,000",
        "Weight": "59g",
        "Battery Life": "Up to 72 hours",
        "Connectivity": "2.4GHz, Bluetooth & Wired",
        "Buttons": "5 Programmable Buttons"
      },
      created_at: "2023-03-12T00:00:00Z",
      updated_at: "2023-08-05T00:00:00Z",
      rating: 4.3,
      review_count: 115,
      reviews: [],
      threads: [],
      upvotes: 138,
      downvotes: 35,
      score: 103,
      rank: 13
    },
    {
      id: uuidv4(),
      name: "ROCCAT Kone Pro Air",
      description: "Ergonomic wireless gaming mouse with unique Titan optical switches",
      category: "mice",
      price: 129.99,
      url_slug: "roccat-kone-pro-air",
      image_url: "/images/products/kone-pro-air.jpg",
      imageUrl: "/images/products/kone-pro-air.jpg",
      specifications: {
        "Sensor": "Owl-Eye 19K",
        "DPI Range": "100-19,000",
        "Weight": "75g",
        "Battery Life": "Up to 100 hours",
        "Connectivity": "2.4GHz & Bluetooth",
        "Buttons": "5 Programmable Buttons"
      },
      created_at: "2023-05-05T00:00:00Z",
      updated_at: "2023-10:05T00:00:00Z",
      rating: 4.4,
      review_count: 96,
      reviews: [],
      threads: [],
      upvotes: 132,
      downvotes: 33,
      score: 99,
      rank: 14
    },
    {
      id: uuidv4(),
      name: "Fnatic BOLT",
      description: "Lightweight wireless esports gaming mouse",
      category: "mice",
      price: 89.99,
      url_slug: "fnatic-bolt",
      image_url: "/images/products/fnatic-bolt.jpg",
      imageUrl: "/images/products/fnatic-bolt.jpg",
      specifications: {
        "Sensor": "PixArt PAW3370",
        "DPI Range": "100-19,000",
        "Weight": "67g",
        "Battery Life": "Up to 110 hours",
        "Connectivity": "2.4GHz Wireless",
        "Buttons": "6 Programmable Buttons"
      },
      created_at: "2023-02-22T00:00:00Z",
      updated_at: "2023-07:28T00:00:00Z",
      rating: 4.5,
      review_count: 88,
      reviews: [],
      threads: [],
      upvotes: 125,
      downvotes: 28,
      score: 97,
      rank: 15
    },
    {
      id: uuidv4(),
      name: "Pwnage Ultra Custom Wireless",
      description: "Modular gaming mouse with swappable shells and buttons",
      category: "mice",
      price: 89.99,
      url_slug: "pwnage-ultra-custom-wireless",
      image_url: "/images/products/pwnage-ultra.jpg",
      imageUrl: "/images/products/pwnage-ultra.jpg",
      specifications: {
        "Sensor": "PixArt PAW3335",
        "DPI Range": "100-16,000",
        "Weight": "69g",
        "Battery Life": "Up to 40 hours",
        "Connectivity": "2.4GHz Wireless",
        "Buttons": "6 Programmable Buttons"
      },
      created_at: "2023-03-30T00:00:00Z",
      updated_at: "2023-08:25T00:00:00Z",
      rating: 4.3,
      review_count: 95,
      reviews: [],
      threads: [],
      upvotes: 118,
      downvotes: 26,
      score: 92,
      rank: 16
    },
    {
      id: uuidv4(),
      name: "Corsair M65 RGB Ultra Wireless",
      description: "Wireless gaming mouse with tunable weight and 8K polling rate",
      category: "mice",
      price: 129.99,
      url_slug: "corsair-m65-rgb-ultra-wireless",
      image_url: "/images/products/m65-ultra.jpg",
      imageUrl: "/images/products/m65-ultra.jpg",
      specifications: {
        "Sensor": "Marksman 26K",
        "DPI Range": "100-26,000",
        "Weight": "97-115g (Adjustable)",
        "Battery Life": "Up to 90 hours",
        "Connectivity": "Slipstream Wireless & Bluetooth",
        "Buttons": "8 Programmable Buttons"
      },
      created_at: "2023-04-15T00:00:00Z",
      updated_at: "2023-09:18T00:00:00Z",
      rating: 4.4,
      review_count: 105,
      reviews: [],
      threads: [],
      upvotes: 112,
      downvotes: 25,
      score: 87,
      rank: 17
    },
    {
      id: uuidv4(),
      name: "MSI Clutch GM41 Lightweight Wireless",
      description: "Lightweight wireless gaming mouse for FPS gamers",
      category: "mice",
      price: 94.99,
      url_slug: "msi-clutch-gm41-lightweight-wireless",
      image_url: "/images/products/clutch-gm41.jpg",
      imageUrl: "/images/products/clutch-gm41.jpg",
      specifications: {
        "Sensor": "PixArt PAW3370",
        "DPI Range": "100-20,000",
        "Weight": "74g",
        "Battery Life": "Up to 80 hours",
        "Connectivity": "2.4GHz Wireless",
        "Buttons": "6 Programmable Buttons"
      },
      created_at: "2023-05-12T00:00:00Z",
      updated_at: "2023-10:22T00:00:00Z",
      rating: 4.3,
      review_count: 86,
      reviews: [],
      threads: [],
      upvotes: 105,
      downvotes: 24,
      score: 81,
      rank: 18
    },
    {
      id: uuidv4(),
      name: "Lamzu Atlantis Mini",
      description: "Ultra-lightweight wireless gaming mouse with compact design",
      category: "mice",
      price: 109.99,
      url_slug: "lamzu-atlantis-mini",
      image_url: "/images/products/lamzu-atlantis.jpg",
      imageUrl: "/images/products/lamzu-atlantis.jpg",
      specifications: {
        "Sensor": "PixArt PAW3395",
        "DPI Range": "50-26,000",
        "Weight": "52g",
        "Battery Life": "Up to 70 hours",
        "Connectivity": "2.4GHz Wireless",
        "Buttons": "5 Programmable Buttons"
      },
      created_at: "2023-06-08T00:00:00Z",
      updated_at: "2023-11:15T00:00:00Z",
      rating: 4.6,
      review_count: 76,
      reviews: [],
      threads: [],
      upvotes: 98,
      downvotes: 18,
      score: 80,
      rank: 19
    },
    {
      id: uuidv4(),
      name: "Logitech G305 LIGHTSPEED",
      description: "Affordable wireless gaming mouse with HERO sensor",
      category: "mice",
      price: 49.99,
      url_slug: "logitech-g305-lightspeed",
      image_url: "/images/products/g305.jpg",
      imageUrl: "/images/products/g305.jpg",
      specifications: {
        "Sensor": "HERO",
        "DPI Range": "200-12,000",
        "Weight": "99g",
        "Battery Life": "Up to 250 hours",
        "Connectivity": "LIGHTSPEED Wireless",
        "Buttons": "6 Programmable Buttons"
      },
      created_at: "2023-01-15T00:00:00Z",
      updated_at: "2023-06:20T00:00:00Z",
      rating: 4.7,
      review_count: 245,
      reviews: [],
      threads: [],
      upvotes: 95,
      downvotes: 17,
      score: 78,
      rank: 20
    }
  ];
} 