import { Product } from "@/types/product";
import { v4 as uuidv4 } from 'uuid';

/**
 * Generate additional monitor products to expand the database
 */
export function generateAdditionalMonitors(): Product[] {
  return [
    {
      id: uuidv4(),
      name: "Dell Alienware AW3423DW",
      description: "34-inch QD-OLED curved gaming monitor with 175Hz refresh rate and G-SYNC Ultimate",
      category: "monitors",
      price: 1299.99,
      url_slug: "dell-alienware-aw3423dw",
      image_url: "/images/products/alienware-aw3423dw.jpg",
      specifications: {
        "Panel Type": "QD-OLED",
        "Resolution": "3440 x 1440 (UWQHD)",
        "Refresh Rate": "175Hz",
        "Response Time": "0.1ms GtG",
        "HDR": "DisplayHDR True Black 400",
        "Connectivity": "2x DisplayPort 1.4, 1x HDMI 2.0"
      },
      created_at: "2023-05-15T00:00:00Z",
      updated_at: "2023-09-05T00:00:00Z",
      rating: 4.9,
      review_count: 176,
      reviews: [],
      threads: []
    },
    {
      id: uuidv4(),
      name: "MSI Optix MAG274QRF-QD",
      description: "27-inch Rapid IPS gaming monitor with Quantum Dot technology and 165Hz refresh rate",
      category: "monitors",
      price: 549.99,
      url_slug: "msi-optix-mag274qrf-qd",
      image_url: "/images/products/msi-mag274qrf.jpg",
      specifications: {
        "Panel Type": "Rapid IPS",
        "Resolution": "2560 x 1440 (QHD)",
        "Refresh Rate": "165Hz",
        "Response Time": "1ms GtG",
        "HDR": "HDR Ready",
        "Connectivity": "1x DisplayPort 1.4, 2x HDMI 2.0b, 1x USB-C"
      },
      created_at: "2023-06-10T00:00:00Z",
      updated_at: "2023-10-22T00:00:00Z",
      rating: 4.7,
      review_count: 142,
      reviews: [],
      threads: []
    },
    {
      id: uuidv4(),
      name: "LG 34GP83A-B",
      description: "34-inch UltraGear curved gaming monitor with 144Hz refresh rate and Nano IPS panel",
      category: "monitors",
      price: 799.99,
      url_slug: "lg-34gp83a-b",
      image_url: "/images/products/lg-34gp83a.jpg",
      specifications: {
        "Panel Type": "Nano IPS",
        "Resolution": "3440 x 1440 (UWQHD)",
        "Refresh Rate": "144Hz",
        "Response Time": "1ms GtG",
        "HDR": "VESA DisplayHDR 400",
        "Connectivity": "2x HDMI 2.0, 1x DisplayPort 1.4"
      },
      created_at: "2023-03-08T00:00:00Z",
      updated_at: "2023-08-12T00:00:00Z",
      rating: 4.6,
      review_count: 198,
      reviews: [],
      threads: []
    },
    {
      id: uuidv4(),
      name: "ASUS ROG Swift PG259QN",
      description: "24.5-inch gaming monitor with 360Hz refresh rate and Fast IPS panel",
      category: "monitors",
      price: 699.99,
      url_slug: "asus-rog-swift-pg259qn",
      image_url: "/images/products/asus-pg259qn.jpg",
      specifications: {
        "Panel Type": "Fast IPS",
        "Resolution": "1920 x 1080 (FHD)",
        "Refresh Rate": "360Hz",
        "Response Time": "1ms GtG",
        "HDR": "HDR10",
        "Connectivity": "1x DisplayPort 1.4, 2x HDMI 2.0"
      },
      created_at: "2023-02-18T00:00:00Z",
      updated_at: "2023-07-05T00:00:00Z",
      rating: 4.8,
      review_count: 156,
      reviews: [],
      threads: []
    },
    {
      id: uuidv4(),
      name: "BenQ ZOWIE XL2546K",
      description: "24.5-inch esports gaming monitor with 240Hz refresh rate and DyAc+ technology",
      category: "monitors",
      price: 549.99,
      url_slug: "benq-zowie-xl2546k",
      image_url: "/images/products/benq-xl2546k.jpg",
      specifications: {
        "Panel Type": "TN",
        "Resolution": "1920 x 1080 (FHD)",
        "Refresh Rate": "240Hz",
        "Response Time": "0.5ms GtG",
        "HDR": "None",
        "Connectivity": "3x HDMI 2.0, 1x DisplayPort 1.4"
      },
      created_at: "2023-01-30T00:00:00Z",
      updated_at: "2023-06-22T00:00:00Z",
      rating: 4.7,
      review_count: 187,
      reviews: [],
      threads: []
    },
    {
      id: uuidv4(),
      name: "Acer Predator X38",
      description: "37.5-inch curved UltraWide gaming monitor with 175Hz refresh rate",
      category: "monitors",
      price: 1699.99,
      url_slug: "acer-predator-x38",
      image_url: "/images/products/acer-predator-x38.jpg",
      specifications: {
        "Panel Type": "IPS",
        "Resolution": "3840 x 1600 (UWQHD+)",
        "Refresh Rate": "175Hz",
        "Response Time": "1ms GtG",
        "HDR": "VESA DisplayHDR 400",
        "Connectivity": "1x DisplayPort 1.4, 1x HDMI 2.0"
      },
      created_at: "2023-04-05T00:00:00Z",
      updated_at: "2023-09-18T00:00:00Z",
      rating: 4.5,
      review_count: 124,
      reviews: [],
      threads: []
    },
    {
      id: uuidv4(),
      name: "AOC AGON AG273QZ",
      description: "27-inch QHD gaming monitor with 240Hz refresh rate and 0.5ms response time",
      category: "monitors",
      price: 629.99,
      url_slug: "aoc-agon-ag273qz",
      image_url: "/images/products/aoc-ag273qz.jpg",
      specifications: {
        "Panel Type": "TN",
        "Resolution": "2560 x 1440 (QHD)",
        "Refresh Rate": "240Hz",
        "Response Time": "0.5ms MPRT",
        "HDR": "HDR10",
        "Connectivity": "2x DisplayPort 1.4, 2x HDMI 2.0"
      },
      created_at: "2023-03-22T00:00:00Z",
      updated_at: "2023-08-14T00:00:00Z",
      rating: 4.3,
      review_count: 132,
      reviews: [],
      threads: []
    },
    {
      id: uuidv4(),
      name: "Gigabyte M32U",
      description: "32-inch 4K IPS gaming monitor with 144Hz refresh rate and HDMI 2.1",
      category: "monitors",
      price: 799.99,
      url_slug: "gigabyte-m32u",
      image_url: "/images/products/gigabyte-m32u.jpg",
      specifications: {
        "Panel Type": "SS IPS",
        "Resolution": "3840 x 2160 (UHD 4K)",
        "Refresh Rate": "144Hz",
        "Response Time": "1ms MPRT",
        "HDR": "VESA DisplayHDR 400",
        "Connectivity": "1x DisplayPort 1.4, 2x HDMI 2.1, 1x USB-C"
      },
      created_at: "2023-05-11T00:00:00Z",
      updated_at: "2023-10-05T00:00:00Z",
      rating: 4.6,
      review_count: 145,
      reviews: [],
      threads: []
    },
    {
      id: uuidv4(),
      name: "Alienware 25 AW2521HF",
      description: "24.5-inch FHD IPS gaming monitor with 240Hz refresh rate",
      category: "monitors",
      price: 399.99,
      url_slug: "alienware-25-aw2521hf",
      image_url: "/images/products/alienware-aw2521hf.jpg",
      specifications: {
        "Panel Type": "Fast IPS",
        "Resolution": "1920 x 1080 (FHD)",
        "Refresh Rate": "240Hz",
        "Response Time": "1ms GtG",
        "HDR": "None",
        "Connectivity": "1x DisplayPort 1.2, 2x HDMI 2.0"
      },
      created_at: "2023-02-25T00:00:00Z",
      updated_at: "2023-07-18T00:00:00Z",
      rating: 4.7,
      review_count: 215,
      reviews: [],
      threads: []
    },
    {
      id: uuidv4(),
      name: "ViewSonic Elite XG270QG",
      description: "27-inch QHD IPS gaming monitor with 165Hz refresh rate and G-SYNC",
      category: "monitors",
      price: 599.99,
      url_slug: "viewsonic-elite-xg270qg",
      image_url: "/images/products/viewsonic-xg270qg.jpg",
      specifications: {
        "Panel Type": "IPS",
        "Resolution": "2560 x 1440 (QHD)",
        "Refresh Rate": "165Hz",
        "Response Time": "1ms MPRT",
        "HDR": "None",
        "Connectivity": "1x DisplayPort 1.2, 1x HDMI 1.4"
      },
      created_at: "2023-03-05T00:00:00Z",
      updated_at: "2023-08-22T00:00:00Z",
      rating: 4.5,
      review_count: 168,
      reviews: [],
      threads: []
    },
    {
      id: uuidv4(),
      name: "Eve Spectrum ES07D03",
      description: "27-inch QHD IPS gaming monitor with 240Hz refresh rate and HDMI 2.1",
      category: "monitors",
      price: 799.99,
      url_slug: "eve-spectrum-es07d03",
      image_url: "/images/products/eve-spectrum.jpg",
      specifications: {
        "Panel Type": "Nano IPS",
        "Resolution": "2560 x 1440 (QHD)",
        "Refresh Rate": "240Hz",
        "Response Time": "1ms GtG",
        "HDR": "VESA DisplayHDR 600",
        "Connectivity": "1x DisplayPort 1.4, 2x HDMI 2.1, 1x USB-C"
      },
      created_at: "2023-06-15T00:00:00Z",
      updated_at: "2023-11-08T00:00:00Z",
      rating: 4.4,
      review_count: 98,
      reviews: [],
      threads: []
    },
    {
      id: uuidv4(),
      name: "Samsung Odyssey Neo G8",
      description: "32-inch 4K curved gaming monitor with Mini LED and 240Hz refresh rate",
      category: "monitors",
      price: 1299.99,
      url_slug: "samsung-odyssey-neo-g8",
      image_url: "/images/products/samsung-neo-g8.jpg",
      specifications: {
        "Panel Type": "VA with Mini LED",
        "Resolution": "3840 x 2160 (UHD 4K)",
        "Refresh Rate": "240Hz",
        "Response Time": "1ms GtG",
        "HDR": "VESA DisplayHDR 2000",
        "Connectivity": "1x DisplayPort 1.4, 2x HDMI 2.1"
      },
      created_at: "2023-07-20T00:00:00Z",
      updated_at: "2023-12-05T00:00:00Z",
      rating: 4.7,
      review_count: 115,
      reviews: [],
      threads: []
    },
    {
      id: uuidv4(),
      name: "Corsair XENEON 32QHD165",
      description: "32-inch QHD gaming monitor with 165Hz refresh rate and Quantum Dot",
      category: "monitors",
      price: 699.99,
      url_slug: "corsair-xeneon-32qhd165",
      image_url: "/images/products/corsair-xeneon.jpg",
      specifications: {
        "Panel Type": "IPS Quantum Dot",
        "Resolution": "2560 x 1440 (QHD)",
        "Refresh Rate": "165Hz",
        "Response Time": "1ms MPRT",
        "HDR": "VESA DisplayHDR 400",
        "Connectivity": "1x DisplayPort 1.4, 2x HDMI 2.0, 1x USB-C"
      },
      created_at: "2023-05-25T00:00:00Z",
      updated_at: "2023-10-18T00:00:00Z",
      rating: 4.5,
      review_count: 126,
      reviews: [],
      threads: []
    },
    {
      id: uuidv4(),
      name: "Acer Nitro XV340CK",
      description: "34-inch UltraWide IPS gaming monitor with 144Hz refresh rate",
      category: "monitors",
      price: 449.99,
      url_slug: "acer-nitro-xv340ck",
      image_url: "/images/products/acer-nitro-xv340ck.jpg",
      specifications: {
        "Panel Type": "IPS",
        "Resolution": "3440 x 1440 (UWQHD)",
        "Refresh Rate": "144Hz",
        "Response Time": "1ms VRB",
        "HDR": "HDR10",
        "Connectivity": "2x DisplayPort 1.4, 2x HDMI 2.0"
      },
      created_at: "2023-04-12T00:00:00Z",
      updated_at: "2023-09-30T00:00:00Z",
      rating: 4.3,
      review_count: 153,
      reviews: [],
      threads: []
    },
    {
      id: uuidv4(),
      name: "ASUS TUF Gaming VG259QM",
      description: "24.5-inch Full HD gaming monitor with 280Hz refresh rate",
      category: "monitors",
      price: 319.99,
      url_slug: "asus-tuf-gaming-vg259qm",
      image_url: "/images/products/asus-vg259qm.jpg",
      specifications: {
        "Panel Type": "Fast IPS",
        "Resolution": "1920 x 1080 (FHD)",
        "Refresh Rate": "280Hz (OC)",
        "Response Time": "1ms MPRT",
        "HDR": "DisplayHDR 400",
        "Connectivity": "2x HDMI 2.0, 1x DisplayPort 1.2"
      },
      created_at: "2023-03-18T00:00:00Z",
      updated_at: "2023-08-24T00:00:00Z",
      rating: 4.6,
      review_count: 187,
      reviews: [],
      threads: []
    },
    {
      id: uuidv4(),
      name: "MSI MPG ARTYMIS 343CQR",
      description: "34-inch super curved ultrawide gaming monitor with 165Hz refresh rate",
      category: "monitors",
      price: 899.99,
      url_slug: "msi-mpg-artymis-343cqr",
      image_url: "/images/products/msi-artymis.jpg",
      specifications: {
        "Panel Type": "VA",
        "Resolution": "3440 x 1440 (UWQHD)",
        "Refresh Rate": "165Hz",
        "Response Time": "1ms MPRT",
        "HDR": "VESA DisplayHDR 400",
        "Curvature": "1000R",
        "Connectivity": "1x DisplayPort 1.4, 2x HDMI 2.0, 1x USB-C"
      },
      created_at: "2023-06-05T00:00:00Z",
      updated_at: "2023-11-15T00:00:00Z",
      rating: 4.4,
      review_count: 112,
      reviews: [],
      threads: []
    },
    {
      id: uuidv4(),
      name: "Gigabyte G27Q",
      description: "27-inch QHD gaming monitor with 144Hz refresh rate and FreeSync Premium",
      category: "monitors",
      price: 329.99,
      url_slug: "gigabyte-g27q",
      image_url: "/images/products/gigabyte-g27q.jpg",
      specifications: {
        "Panel Type": "IPS",
        "Resolution": "2560 x 1440 (QHD)",
        "Refresh Rate": "144Hz",
        "Response Time": "1ms MPRT",
        "HDR": "HDR Ready",
        "Connectivity": "2x HDMI 2.0, 1x DisplayPort 1.2"
      },
      created_at: "2023-02-08T00:00:00Z",
      updated_at: "2023-07-12T00:00:00Z",
      rating: 4.5,
      review_count: 205,
      reviews: [],
      threads: []
    },
    {
      id: uuidv4(),
      name: "LG UltraGear 48GQ900-B",
      description: "47.5-inch OLED gaming monitor with 138Hz refresh rate and anti-glare coating",
      category: "monitors",
      price: 1499.99,
      url_slug: "lg-ultragear-48gq900-b",
      image_url: "/images/products/lg-48gq900.jpg",
      specifications: {
        "Panel Type": "OLED",
        "Resolution": "3840 x 2160 (UHD 4K)",
        "Refresh Rate": "138Hz",
        "Response Time": "0.1ms GtG",
        "HDR": "HDR10",
        "Connectivity": "3x HDMI 2.1, 1x DisplayPort 1.4"
      },
      created_at: "2023-07-10T00:00:00Z",
      updated_at: "2023-12-15T00:00:00Z",
      rating: 4.8,
      review_count: 89,
      reviews: [],
      threads: []
    },
    {
      id: uuidv4(),
      name: "Acer Predator XB273K",
      description: "27-inch 4K IPS gaming monitor with 144Hz refresh rate",
      category: "monitors",
      price: 899.99,
      url_slug: "acer-predator-xb273k",
      image_url: "/images/products/acer-predator-xb273k.jpg",
      specifications: {
        "Panel Type": "IPS",
        "Resolution": "3840 x 2160 (UHD 4K)",
        "Refresh Rate": "144Hz",
        "Response Time": "1ms VRB",
        "HDR": "VESA DisplayHDR 400",
        "Connectivity": "2x DisplayPort 1.4, 2x HDMI 2.0"
      },
      created_at: "2023-04-20T00:00:00Z",
      updated_at: "2023-09-22T00:00:00Z",
      rating: 4.5,
      review_count: 132,
      reviews: [],
      threads: []
    },
    {
      id: uuidv4(),
      name: "Philips Momentum 559M1RYV",
      description: "55-inch 4K Mini LED gaming monitor with 144Hz refresh rate and Ambiglow",
      category: "monitors",
      price: 1599.99,
      url_slug: "philips-momentum-559m1ryv",
      image_url: "/images/products/philips-momentum.jpg",
      specifications: {
        "Panel Type": "VA with Mini LED",
        "Resolution": "3840 x 2160 (UHD 4K)",
        "Refresh Rate": "144Hz",
        "Response Time": "4ms GtG",
        "HDR": "VESA DisplayHDR 1000",
        "Connectivity": "3x HDMI 2.1, 1x DisplayPort 1.4"
      },
      created_at: "2023-06-22T00:00:00Z",
      updated_at: "2023-11-25T00:00:00Z",
      rating: 4.6,
      review_count: 76,
      reviews: [],
      threads: []
    }
  ];
} 